version: "3.9"

services:

  hotel:
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:

      HOTEL_MONGO_URI: mongodb://mongo:27017/hoteldb
    depends_on:
      - mongo
    networks:
      - backend

  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "9000:27017"
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: hoteldb
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

volumes:
  mongo_data:

networks:
  backend:
    driver: bridge