events {}

http {
    upstream search_upstream {
        server search-service:8080;
    }
    upstream booking_upstream {
        server booking-service:8080;
    }

    server {
        listen 80;
        location /api/search/ {
            proxy_pass http://search_upstream;
        }
        location /api/ {
            proxy_pass http://booking_upstream;
        }
    }
}