events {}

http {
    upstream searchservice {
        server search-service:8080;
    }
    upstream bookingservice {
        server booking-service:8080;
    }
    upstream userservice {
        server user-service:8080;
    }

    server {
        listen 80;
        location /api/search/ {
            proxy_pass http://searchservice;
        }

        location /api/users/ {
            proxy_pass http://userservice;
        }

        location /api/bookings {
            proxy_pass http://bookingservice;
        }
    }
}